# Generated by Django 6.0.3 on 2026-03-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('intrest1', models.CharField(blank=True, max_length=100)),
                ('intrest2', models.CharField(blank=True, max_length=100)),
                ('intrest3', models.CharField(blank=True, max_length=100)),
                ('intrest4', models.CharField(blank=True, max_length=100)),
                ('diamonds', models.PositiveIntegerField(default=0)),
                ('profilepicture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
            ],
        ),
    ]
