# Generated by Django 6.0.3 on 2026-03-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='diamonds',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
